#!/bin/sh
case $# in
0) echo "This scripts lists all the words contained in a dictionary.
Usage: wordlist [-s | -p] <dictionary>
<dictionary> is expected to be a path to hunspell .dic and .aff files.
-s: print only suffixed forms
-p: print only prefixed forms
"; exit 1;;
esac
fx=0
case $1 in
-s) fx=1; shift;;
-p) fx=2; shift;;
esac

count=

dicfile="$1.dic"
afffile="$1.aff"
while read dictline; do
count=$((count + 1)) #line counter
if [ "$count" -gt 1 ]; then #&& [$dictline -ne '']; then
test -h /tmp/wordlist.aff && rm /tmp/wordlist.aff
ln -s $PWD/$afffile /tmp/wordlist.aff
# prepared dic only with the query word
echo 1 >/tmp/wordlist.dic
echo $dictline >>/tmp/wordlist.dic
word=`echo $dictline | awk 'BEGIN {FS="/"}{print $1}'`
echo $word | awk -v "fx=$fx" '
fx!=2 && FILENAME!="-" && /^SFX/ && NF > 4{split($4,a,"/");clen=($3=="0") ? 0 : length($3);sfx[a[1],clen]=a[1];sfxc[a[1],clen]=clen;next}
fx!=1 && FILENAME!="-" && /^PFX/ && NF > 4{split($4,a,"/");clen=($3=="0") ? 0 : length($3);pfx[a[1],clen]=a[1];pfxc[a[1],clen]=clen;next}
FILENAME=="-"{
wlen=length($1)
if (fx==0 || fx==2) {
    for (j in pfx) {if (wlen<=pfxc[j]) continue; print (pfx[j]=="0" ? "" : pfx[j]) substr($1, pfxc[j]+1)}
}
if (fx==0 || fx==1) {
  for(i in sfx){clen=sfxc[i];if (wlen<=clen) continue; print substr($1, 1, wlen-clen) (sfx[i]=="0" ? "": sfx[i]) }
}
if (fx==0) {
for (j in pfx) {if (wlen<=pfxc[j]) continue;
  for(i in sfx){clen=sfxc[i];if (wlen<=clen || wlen <= (clen + pfxc[j]))continue;
      print (pfx[j]=="0" ? "" : pfx[j]) substr($1, pfxc[j]+1, wlen-clen-pfxc[j]) (sfx[i]=="0" ? "": sfx[i]) }}
}
} 
' /tmp/wordlist.aff - | hunspell -d /tmp/wordlist -G -l
fi
done < $dicfile
